// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MilkAndMoon.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Baby", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_babies");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_babies_user_id");

                    b.ToTable("babies", (string)null);
                });

            modelBuilder.Entity("DiaperLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BabyId")
                        .HasColumnType("uuid")
                        .HasColumnName("baby_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DiaperType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("diaper_type");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PeeColor")
                        .HasColumnType("text")
                        .HasColumnName("pee_color");

                    b.Property<string>("Rash")
                        .HasColumnType("text")
                        .HasColumnName("rash");

                    b.PrimitiveCollection<string[]>("RashLocation")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("rash_location")
                        .HasDefaultValueSql("'{}'");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.PrimitiveCollection<string[]>("StoolColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("stool_color")
                        .HasDefaultValueSql("'{}'");

                    b.PrimitiveCollection<string[]>("StoolTexture")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("stool_texture")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_diaper_logs");

                    b.HasIndex("BabyId")
                        .HasDatabaseName("ix_diaper_logs_baby_id");

                    b.ToTable("diaper_logs", null, t =>
                        {
                            t.HasCheckConstraint("diaper_logs_diaper_types", "diaper_type IN ('wet','poopy','both')");

                            t.HasCheckConstraint("diaper_logs_pee_colors", "pee_color IN ('clear','light yellow','dark yellow','orange')");

                            t.HasCheckConstraint("diaper_logs_rash", "rash IN ('mild','moderate','severe')");

                            t.HasCheckConstraint("diaper_logs_rash_locations", "rash_location <@ ARRAY['front','back','folds','aroundAnus','other']::text[]");

                            t.HasCheckConstraint("diaper_logs_stool_colors", "stool_color <@ ARRAY['black','yellow','green','brown','red','white','other']::text[]");

                            t.HasCheckConstraint("diaper_logs_stool_textures", "stool_texture <@ ARRAY['seedy','soft','loose','watery','mucus','hard','other']::text[]");
                        });
                });

            modelBuilder.Entity("FeedLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BabyId")
                        .HasColumnType("uuid")
                        .HasColumnName("baby_id");

                    b.Property<decimal>("BottleSize")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)")
                        .HasDefaultValue(0m)
                        .HasColumnName("bottle_size");

                    b.PrimitiveCollection<string[]>("BreastSide")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("breast_side")
                        .HasDefaultValueSql("'{}'");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("FeedType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("feed_type");

                    b.Property<decimal>("MilkConsumed")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)")
                        .HasDefaultValue(0m)
                        .HasColumnName("milk_consumed");

                    b.PrimitiveCollection<string[]>("MilkType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("milk_type")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_feed_logs");

                    b.HasIndex("BabyId")
                        .HasDatabaseName("ix_feed_logs_baby_id");

                    b.ToTable("feed_logs", null, t =>
                        {
                            t.HasCheckConstraint("feed_logs_breast_side", "breast_side <@ ARRAY['left','right']::text[]");

                            t.HasCheckConstraint("feed_logs_feed_type", "feed_type IN ('bottle', 'breast')");

                            t.HasCheckConstraint("feed_logs_milk_type", "milk_type <@ ARRAY['breastmilk','formula']::text[]");
                        });
                });

            modelBuilder.Entity("PumpLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BabyId")
                        .HasColumnType("uuid")
                        .HasColumnName("baby_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<decimal>("LeftAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)")
                        .HasDefaultValue(0m)
                        .HasColumnName("left_amount");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal>("RightAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)")
                        .HasDefaultValue(0m)
                        .HasColumnName("right_amount");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_pump_logs");

                    b.HasIndex("BabyId")
                        .HasDatabaseName("ix_pump_logs_baby_id");

                    b.ToTable("pump_logs", (string)null);
                });

            modelBuilder.Entity("SleepLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BabyId")
                        .HasColumnType("uuid")
                        .HasColumnName("baby_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.PrimitiveCollection<string[]>("WakeReasons")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("wake_reasons")
                        .HasDefaultValueSql("'{}'");

                    b.HasKey("Id")
                        .HasName("pk_sleep_logs");

                    b.HasIndex("BabyId")
                        .HasDatabaseName("ix_sleep_logs_baby_id");

                    b.ToTable("sleep_logs", null, t =>
                        {
                            t.HasCheckConstraint("sleep_logs_locations", "location IN ('bassinet','crib','contactNap','stroller','car','other')");

                            t.HasCheckConstraint("sleep_logs_wake_reasons", "wake_reasons <@ ARRAY['hungry','diaper','naturally','noise','moved','unknown']::text[]");
                        });
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Baby", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_babies_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DiaperLog", b =>
                {
                    b.HasOne("Baby", "Baby")
                        .WithMany()
                        .HasForeignKey("BabyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_diaper_logs_babies_baby_id");

                    b.Navigation("Baby");
                });

            modelBuilder.Entity("FeedLog", b =>
                {
                    b.HasOne("Baby", "Baby")
                        .WithMany()
                        .HasForeignKey("BabyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_feed_logs_babies_baby_id");

                    b.Navigation("Baby");
                });

            modelBuilder.Entity("PumpLog", b =>
                {
                    b.HasOne("Baby", "Baby")
                        .WithMany()
                        .HasForeignKey("BabyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pump_logs_babies_baby_id");

                    b.Navigation("Baby");
                });

            modelBuilder.Entity("SleepLog", b =>
                {
                    b.HasOne("Baby", "Baby")
                        .WithMany()
                        .HasForeignKey("BabyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sleep_logs_babies_baby_id");

                    b.Navigation("Baby");
                });
#pragma warning restore 612, 618
        }
    }
}
